#!/usr/bin/env python
from sys import argv, exit


def custom_help():
    from rich.console import Console
    from rich.panel import Panel
    from rich.table import Table
    from rich.table import box

    console = Console()

    header = Panel.fit(
        "[cyan bold]    Welcome to PropClip-Analyzer![/cyan bold]    ",
        border_style="purple",
        box=box.ROUNDED,
    )
    console.print(header)

    # Commands Table
    commands = Table(box=box.SIMPLE_HEAVY)
    commands.add_column("Command  ", style="bold bright_blue", no_wrap=True)
    commands.add_column("")
    commands.add_column("Description", style="default")
    commands.add_row("record",     "[red]->[default]",   "Record input pastes")
    commands.add_row("manage",      "[red]->[default]",   "View records and manage")
    commands.add_row("process", "[red]->[default]",   "Process records with Gemini")


    console.print(commands)
    console.print("'[bold yellow]pclip <[green]cmd[/green]> --help[/bold yellow]' for specific help.\n")

# Catch [--help | -h] command (Performance)
args = argv[1:]
if not args or args[0] in ["--help", "-h"]:
    custom_help()
    exit(0)

if __name__ == "__main__":
    from cli import app
    app()